### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by WhitePhilosopher** [rohit7044/3DGANTex#1]
Hello, thank you for sharing such an amazing project. Could you please provide the training code? I am a beginner in this field and just starting to learn.

**Comment by rohit7044** [comment]
Hi!
This is an inference model which has pre-trained weights of Stylegan3,3DDFAv2 and Restyle encoder.
I guess you can check individual repo for training.
What's your use case?

**Comment by rohit7044** [comment]
Since there's no reply, the issue will close in 3 days.
