### ISSUE TITLE
Error: Failed to initialize models: 3D-GANTex directory not found in the current path

### ISSUE THREAD

**Issue by DAnonyvinciT** [rohit7044/3DGANTex#2]
When i run the argument example after all the requirements installed，it come the **error ： Failed to initialize models: 3D-GANTex directory not found in the current path**，how can i fix it ？ thanks

**Comment by rohit7044** [comment]
Have you downloaded the weights?
And can you share the log?

**Comment by rohit7044** [comment]
Since there's no reply, this issue will be closed in 3 days.

**Comment by WYao02** [comment]
Hello, I have the same problem. The log is shown below: 
INFO:face_processor:Using device: cuda
Error: Failed to initialize models: 3D-GANTex directory not found in the current path

**Comment by rohit7044** [comment]
Hi,
Have you created conda environment, downloaded the models and make sure the path is called correctly.
Sometimes it's better to use the full directory path "/mnt/d/Github Repo/3D-GANTex/main.py" due to access issue.

**Comment by rohit7044** [comment]
Closing this since no replies

**Comment by raflitp** [comment]
Hi I'm having the same problem,
INFO:face_processor:Using device: cuda
Error: Failed to initialize models: 3D-GANTex directory not found in the current path

I've downloaded the models but not sure where to place it, I've made conda environment for this as well

**Comment by rohit7044** [comment]
If you follow the instructions, the code should work.

**Comment by raflitp** [comment]
Apparently because the instructions on the repo is said to clone the repo with this method : "git clone https://github.com/rohit7044/3DGANTex" it seems to made the folder to named 3DGantex instead of 3D-Gantex. So I just changed the name of the repo locally to "3D-GANTex" and it works properly

**Comment by rohit7044** [comment]
Thank you for pointing it out. 
I have made the changes in README.md
